/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import javax.swing.JFrame;

/**
 *
 * @author Sadman
 */
public class chatFrame extends javax.swing.JFrame {

    /**
     * Creates new form chatFrame
     */            
    private String title;
    private DataOutputStream dos;    
    public chatFrame(String title, DataOutputStream dos) {
        initComponents();    
        this.setVisible(true);
        this.setTitle(title);
        this.title = title;
        this.dos = dos;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageToSendField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivedMessageArea = new javax.swing.JTextArea();
        receiverNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        messageToSendField.setToolTipText("");
        messageToSendField.setName("");
        messageToSendField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageToSendFieldKeyPressed(evt);
            }
        });

        receivedMessageArea.setColumns(20);
        receivedMessageArea.setEditable(false);
        receivedMessageArea.setLineWrap(true);
        receivedMessageArea.setRows(5);
        jScrollPane1.setViewportView(receivedMessageArea);

        jLabel1.setText("To");

        jLabel2.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageToSendField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageToSendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageToSendFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageToSendFieldKeyPressed
        // TODO add your handling code here:
        int keyCode = evt.getKeyCode();
        if(keyCode == evt.VK_ENTER){
            try{                
                String message = receiverNameField.getText() + ":" + messageToSendField.getText();                
                dos.writeBytes(title + " >> " + message + "\n");                                     
                if(receiverNameField.getText().equals("")) receivedMessageArea.append("Me >> " + messageToSendField.getText() + "\n"); 
                else receivedMessageArea.append("Me >> " + receiverNameField.getText() + " : " + messageToSendField.getText() + "\n");
                receiverNameField.setText("");
                messageToSendField.setText("");
            }catch(Exception e){}
        }
    }//GEN-LAST:event_messageToSendFieldKeyPressed

    /**
     * @param args the command line arguments
     */    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField messageToSendField;
    public javax.swing.JTextArea receivedMessageArea;
    private javax.swing.JTextField receiverNameField;
    // End of variables declaration//GEN-END:variables
}
